# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26aa8ae11617df025473cb32a10456ca9a67b128bcb6d3f3062c42ba51f968c0c01d362079498090c2a2f530310cd1017269df31bb1088d3b825e6feffb38688

test:
  secret_key_base: 8de2c31018c8047c896d7c705a38c3899f88a6ac44b2f133972933130cdb2139ac39427f51d76844a7232d2fc5f09724cfb6249a6f49fead4c41531f095e7802

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
